services:
  cerebro:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      - AUTH_TYPE=ldap
      - LDAP_URL=ldap://ldap:389
      - LDAP_BASE_DN=DC=example,DC=org
      - LDAP_METHOD=simple
      - LDAP_USER_TEMPLATE=uid=%s,%s
    ports:
      - "9000:9000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.27
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  open_ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./users:/opt
